FROM node:12.18.1
ENV NODE_ENV=production

WORKDIR /app

COPY ["./environment/package.json", "./environment/package-lock.jsonpackage-lock.json*", "./"]

RUN npm install --production

COPY . .

CMD [ "node", "./environment/index.js" ]